### ISSUE TITLE
Store secrets in the encypted file, uploadable to repo

### ISSUE THREAD

**Issue by efojs** [kakulukia/django-secrets#4]
What do you think about storing encrypted secrets in the file uploadable to the remote repository? 

On production it's auto-decoded via the only master key stored in the ENV, while on development key is stored in the local ENV or git-ignored file.

They use [alike approach in the Rails](https://guides.rubyonrails.org/security.html#environmental-security).

It will:
- let developers in teams share same dev resources, like AWS credentials;
- eliminate the need of exporting and managing multiple ENVs, stored in plain text.

Or maybe I'm missing some Django/Python way to achieve these goals?

**Comment by kakulukia** [comment]
So you were using this method with rails before?
On first sight I don't really like the concept of having different values for the same settings rather than explicitly using dev secrets in the code, but maybe I didn't fully understand your proposal?
I never had to cope with a lot of changes regarding secretes either so this seems like a lot of complexity for no obvious reason.
You still have to copy something be it the master key or the full list of secrets.

**Comment by efojs** [comment]
> You still have to copy something be it the master key or the full list of secrets.

I think I mean that copying/supporting one master key is easier, than several ones.  
Although I currently work alone, I foresee that working in team it will become more complex.  
And I like to hide not only passwords, but also other credentials. So it escalates quickly)

**Comment by kakulukia** [comment]
So I'm going to close this, as there is no urgent need.
One thing that comes to mind tho, ansible has a vault, which might be what you are looking for.
